# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

	# Packages vom lokalen Server holen und andere Server via /etc/hosts bekannt machen
	config.vm.provision "shell", inline: <<-SHELL
		# sudo sed -i -e"1i deb http://192.168.43.90/ubuntu xenial main restricted" /etc/apt/sources.list
	    echo '127.0.0.1 localhost\n192.168.55.101 web01\n192.168.55.100 db01\n192.168.55.102 iam' > /etc/hosts		
SHELL
	
  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.define "db" do |db|
    db.vm.box = "ubuntu/xenial64"
	db.vm.provider "virtualbox" do |vb|
	  vb.memory = "384"  
	end
    db.vm.hostname = "db01"
    db.vm.network "private_network", ip: "192.168.55.100"
    # MySQL Port nur im Private Network sichtbar
	# db.vm.network "forwarded_port", guest:3306, host:3306, auto_correct: false
  	db.vm.provision "shell", path: "db.sh"
  end
  
  config.vm.define "web" do |web|
    web.vm.box = "ubuntu/xenial64"
    web.vm.hostname = "web01"
    web.vm.network "private_network", ip:"192.168.55.101"
	web.vm.network "forwarded_port", guest:80, host:8080, auto_correct: false
	web.vm.provider "virtualbox" do |vb|
	  vb.memory = "256"  
	end   
  	# DO NOT web.vm.synced_folder ".", "/var/www/html" you can't create a symlink in a symlink!
	web.vm.synced_folder ".", "/vagrant"
	web.vm.provision "shell", inline: <<-SHELL
		sudo apt-get update
		sudo apt-get -y install debconf-utils apache2 nmap ufw
		sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password password admin'
		sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password_again password admin'
		sudo apt-get -y install php libapache2-mod-php php-curl php-cli php-mysql php-gd mysql-client  
		# Python backend
		sudo update-alternatives --install /usr/bin/python python /usr/bin/python3.5 1
		sudo update-alternatives --config python
		sudo apt install python3-pip -y
		sudo pip3 install mysql-connector-python
		sudo cp /vagrant/assets/for_web/index.html /var/www/html/
		sudo cp /vagrant/assets/for_web/backend.py /usr/lib/cgi-bin/ && sudo chown www-data /usr/lib/cgi-bin/backend.py && sudo chmod 755 /usr/lib/cgi-bin/backend.py
		sudo mkdir /usr/share/tmp/
		sudo touch /usr/share/tmp/text.txt
		sudo chmod 755 /usr/share/tmp/text.txt
		sudo ln -s /usr/share/tmp/text.txt /var/www/html/text.txt
		sudo cp /vagrant/000-default.conf /etc/apache2/sites-available/
		sudo chown www-data:www-data /usr/share/tmp/text.txt 
		# Admininer SQL UI 
		sudo mkdir /usr/share/adminer
		sudo wget "http://www.adminer.org/latest.php" -O /usr/share/adminer/latest.php
		sudo ln -s /usr/share/adminer/latest.php /usr/share/adminer/adminer.php
		echo "Alias /adminer.php /usr/share/adminer/adminer.php" | sudo tee /etc/apache2/conf-available/adminer.conf
		sudo a2enconf adminer.conf 
		sudo a2enmod cgi
		sudo mkdir -p  /var/www/html/data && sudo chown www-data:www-data /var/www/html/data 
		# Monitoring
		sudo cp /vagrant/cron.root.web01 /var/spool/cron/crontabs/root && sudo chmod 600 /var/spool/cron/crontabs/root
		# Reverse Proxy
		sudo a2enmod proxy
		sudo a2enmod proxy_html
		sudo a2enmod proxy_http
		# Reverse Proxy
		sudo cp /vagrant/001-reverseproxy.conf /etc/apache2/sites-available/
		sudo ln -s /etc/apache2/sites-available/001-reverseproxy.conf /etc/apache2/sites-enabled/
		# Services restart / reload config
		sudo service cron reload
		sudo service apache2 restart 
		# Firewall
		sudo ufw allow 80/tcp 
		sudo ufw allow 22/tcp 
		sudo ufw -f enable	
SHELL
	end  
	
	# Monitoring Server
	config.vm.define "iam" do |iam|
      iam.vm.box = "ubuntu/xenial64"
	  iam.vm.provider "virtualbox" do |vb|
	    vb.memory = "256"  
	  end
      iam.vm.hostname = "iam"
      iam.vm.network "private_network", ip: "192.168.55.102"
      # wird nicht mehr benoetigt, weil Reverse Proxy auf web eingerichtet
      #iam.vm.network "forwarded_port", guest:80, host:8081, auto_correct: false
  	  iam.vm.synced_folder ".", "/vagrant"  	
	  iam.vm.provision "shell", inline: <<-SHELL
		sudo apt-get update
		sudo apt-get -y install debconf-utils apache2
		sudo a2enmod cgi		
		sudo mkdir -p  /var/www/html/data && sudo chown www-data:www-data /var/www/html/data 
		# OpenLDAP mit Admin UI - http://localhost:8081/phpldapadmin
		export DEBIAN_FRONTEND=noninteractive
		sudo debconf-set-selections <<<'slapd slapd/internal/generated_adminpw password admin'
		sudo debconf-set-selections <<<'slapd slapd/password2 password admin'
		sudo debconf-set-selections <<<'slapd slapd/internal/adminpw password admin'
		sudo debconf-set-selections <<<'slapd slapd/password1 password admin'
		sudo apt-get install -y slapd ldap-utils phpldapadmin	
		# Patch Standarddomain
		sudo sed -i -e's/dc=example,dc=com/dc=nodomain/' /etc/phpldapadmin/config.php	
		sudo service apache2 restart 
		# Firewall 
		sudo ufw allow 22/tcp
		sudo ufw allow from 192.168.55.101 to any port 80 
		sudo ufw -f enable		
SHELL
    end
 end
