# 
version: '3'

services:

  db:
    image: mysql
    # https://hub.docker.com/_/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: proposals
      MYSQL_USER: www-data
      MYSQL_PASSWORD: S3cr3tp4ssw0rd
      # create table data ( seq INT PRIMARY KEY AUTO_INCREMENT, uname TEXT, proposal TEXT, created TIMESTAMP DEFAULT CURRENT_TIMESTAMP )
    networks:
        wall_net:
            ipv4_address: 172.20.0.11

  web:
    build: ./web
    ports:
      - "8080:80"
    volumes:
      - /compose/web:/var/www/html
    networks:
        wall_net:
            ipv4_address: 172.20.0.12

  monitor:
    image: google/cadvisor:latest
    ports:
      - "9999:8080"
    networks:
        wall_net:
            ipv4_address: 172.20.0.13

networks:
    wall_net:
        ipam:
            driver: default
            config:
                - subnet: 172.20.0.0/16